/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// Any : Any contains an arbitrary schema along with a URL to help identify the type of the schema.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Any {
    /// A URL/resource name that uniquely identifies the type of the schema.
    #[serde(rename = "@type", skip_serializing_if = "Option::is_none")]
    pub at_type: Option<String>,
}

impl Any {
    /// Any contains an arbitrary schema along with a URL to help identify the type of the schema.
    pub fn new() -> Any {
        Any { at_type: None }
    }
}
