/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BanScriptRequest {
    /// 0 = permanent ban
    #[serde(rename = "banDuration", skip_serializing_if = "Option::is_none")]
    pub ban_duration: Option<i64>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "script", skip_serializing_if = "Option::is_none")]
    pub script: Option<String>,
}

impl BanScriptRequest {
    pub fn new() -> BanScriptRequest {
        BanScriptRequest {
            ban_duration: None,
            reason: None,
            script: None,
        }
    }
}
