/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchFinalizedEvent {
    #[serde(rename = "commitmentTxid", skip_serializing_if = "Option::is_none")]
    pub commitment_txid: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl BatchFinalizedEvent {
    pub fn new() -> BatchFinalizedEvent {
        BatchFinalizedEvent {
            commitment_txid: None,
            id: None,
        }
    }
}
