/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeprecatedSigner {
    #[serde(rename = "cutoffDate", skip_serializing_if = "Option::is_none")]
    pub cutoff_date: Option<String>,
    #[serde(rename = "pubkey", skip_serializing_if = "Option::is_none")]
    pub pubkey: Option<String>,
}

impl DeprecatedSigner {
    pub fn new() -> DeprecatedSigner {
        DeprecatedSigner {
            cutoff_date: None,
            pubkey: None,
        }
    }
}
