/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchStartedEvent {
    #[serde(rename = "batchExpiry", skip_serializing_if = "Option::is_none")]
    pub batch_expiry: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "intentIdHashes", skip_serializing_if = "Option::is_none")]
    pub intent_id_hashes: Option<Vec<String>>,
}

impl BatchStartedEvent {
    pub fn new() -> BatchStartedEvent {
        BatchStartedEvent {
            batch_expiry: None,
            id: None,
            intent_id_hashes: None,
        }
    }
}
