/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeInfo {
    #[serde(rename = "intentFee", skip_serializing_if = "Option::is_none")]
    pub intent_fee: Option<models::IntentFeeInfo>,
    #[serde(rename = "txFeeRate", skip_serializing_if = "Option::is_none")]
    pub tx_fee_rate: Option<String>,
}

impl FeeInfo {
    pub fn new() -> FeeInfo {
        FeeInfo {
            intent_fee: None,
            tx_fee_rate: None,
        }
    }
}
