/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVirtualTxsResponse {
    /// Auth token can be used for other rpcs related to this vtxo/tx that require proof of
    /// ownership.
    #[serde(rename = "authToken", skip_serializing_if = "Option::is_none")]
    pub auth_token: Option<String>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::IndexerPageResponse>,
    #[serde(rename = "txs", skip_serializing_if = "Option::is_none")]
    pub txs: Option<Vec<String>>,
}

impl GetVirtualTxsResponse {
    pub fn new() -> GetVirtualTxsResponse {
        GetVirtualTxsResponse {
            auth_token: None,
            page: None,
            txs: None,
        }
    }
}
