/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVtxosResponse {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::IndexerPageResponse>,
    #[serde(rename = "vtxos", skip_serializing_if = "Option::is_none")]
    pub vtxos: Option<Vec<models::IndexerVtxo>>,
}

impl GetVtxosResponse {
    pub fn new() -> GetVtxosResponse {
        GetVtxosResponse {
            page: None,
            vtxos: None,
        }
    }
}
