/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAssetResponse {
    #[serde(rename = "assetId", skip_serializing_if = "Option::is_none")]
    pub asset_id: Option<String>,
    #[serde(rename = "controlAsset", skip_serializing_if = "Option::is_none")]
    pub control_asset: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
    #[serde(rename = "supply", skip_serializing_if = "Option::is_none")]
    pub supply: Option<String>,
}

impl GetAssetResponse {
    pub fn new() -> GetAssetResponse {
        GetAssetResponse {
            asset_id: None,
            control_asset: None,
            metadata: None,
            supply: None,
        }
    }
}
