/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBalanceResponse {
    #[serde(rename = "connectorsAccount", skip_serializing_if = "Option::is_none")]
    pub connectors_account: Option<models::Balance>,
    #[serde(rename = "mainAccount", skip_serializing_if = "Option::is_none")]
    pub main_account: Option<models::Balance>,
}

impl GetBalanceResponse {
    pub fn new() -> GetBalanceResponse {
        GetBalanceResponse {
            connectors_account: None,
            main_account: None,
        }
    }
}
