/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubscriptionResponse {
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<models::IndexerSubscriptionEvent>,
    #[serde(rename = "heartbeat", skip_serializing_if = "Option::is_none")]
    pub heartbeat: Option<serde_json::Value>,
}

impl GetSubscriptionResponse {
    pub fn new() -> GetSubscriptionResponse {
        GetSubscriptionResponse {
            event: None,
            heartbeat: None,
        }
    }
}
