/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCommitmentTxResponse {
    #[serde(rename = "batches", skip_serializing_if = "Option::is_none")]
    pub batches: Option<std::collections::HashMap<String, models::IndexerBatch>>,
    #[serde(rename = "endedAt", skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<i64>,
    #[serde(rename = "startedAt", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<i64>,
    #[serde(rename = "totalInputAmount", skip_serializing_if = "Option::is_none")]
    pub total_input_amount: Option<i32>,
    #[serde(rename = "totalInputVtxos", skip_serializing_if = "Option::is_none")]
    pub total_input_vtxos: Option<i32>,
    #[serde(rename = "totalOutputAmount", skip_serializing_if = "Option::is_none")]
    pub total_output_amount: Option<i32>,
    #[serde(rename = "totalOutputVtxos", skip_serializing_if = "Option::is_none")]
    pub total_output_vtxos: Option<i32>,
}

impl GetCommitmentTxResponse {
    pub fn new() -> GetCommitmentTxResponse {
        GetCommitmentTxResponse {
            batches: None,
            ended_at: None,
            started_at: None,
            total_input_amount: None,
            total_input_vtxos: None,
            total_output_amount: None,
            total_output_vtxos: None,
        }
    }
}
