/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTransactionsStreamResponse {
    #[serde(rename = "arkTx", skip_serializing_if = "Option::is_none")]
    pub ark_tx: Option<models::TxNotification>,
    #[serde(rename = "commitmentTx", skip_serializing_if = "Option::is_none")]
    pub commitment_tx: Option<models::TxNotification>,
    #[serde(rename = "heartbeat", skip_serializing_if = "Option::is_none")]
    pub heartbeat: Option<serde_json::Value>,
}

impl GetTransactionsStreamResponse {
    pub fn new() -> GetTransactionsStreamResponse {
        GetTransactionsStreamResponse {
            ark_tx: None,
            commitment_tx: None,
            heartbeat: None,
        }
    }
}
