/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVtxoTreeResponse {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::IndexerPageResponse>,
    #[serde(rename = "vtxoTree", skip_serializing_if = "Option::is_none")]
    pub vtxo_tree: Option<Vec<models::IndexerNode>>,
}

impl GetVtxoTreeResponse {
    pub fn new() -> GetVtxoTreeResponse {
        GetVtxoTreeResponse {
            page: None,
            vtxo_tree: None,
        }
    }
}
