/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBatchSweepTransactionsRequest {
    #[serde(rename = "batchOutpoint", skip_serializing_if = "Option::is_none")]
    pub batch_outpoint: Option<models::IndexerOutpoint>,
}

impl GetBatchSweepTransactionsRequest {
    pub fn new() -> GetBatchSweepTransactionsRequest {
        GetBatchSweepTransactionsRequest {
            batch_outpoint: None,
        }
    }
}
