/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVtxoChainRequest {
    #[serde(rename = "outpoint", skip_serializing_if = "Option::is_none")]
    pub outpoint: Option<models::IndexerOutpoint>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::IndexerPageRequest>,
}

impl GetVtxoChainRequest {
    pub fn new() -> GetVtxoChainRequest {
        GetVtxoChainRequest {
            outpoint: None,
            page: None,
        }
    }
}
