/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStatusResponse {
    #[serde(rename = "initialized", skip_serializing_if = "Option::is_none")]
    pub initialized: Option<bool>,
    #[serde(rename = "synced", skip_serializing_if = "Option::is_none")]
    pub synced: Option<bool>,
    #[serde(rename = "unlocked", skip_serializing_if = "Option::is_none")]
    pub unlocked: Option<bool>,
}

impl GetStatusResponse {
    pub fn new() -> GetStatusResponse {
        GetStatusResponse {
            initialized: None,
            synced: None,
            unlocked: None,
        }
    }
}
