/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetScheduledSweepResponse {
    #[serde(rename = "sweeps", skip_serializing_if = "Option::is_none")]
    pub sweeps: Option<Vec<models::ScheduledSweep>>,
}

impl GetScheduledSweepResponse {
    pub fn new() -> GetScheduledSweepResponse {
        GetScheduledSweepResponse { sweeps: None }
    }
}
