/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConvictionsByRoundRequest {
    #[serde(rename = "roundId", skip_serializing_if = "Option::is_none")]
    pub round_id: Option<String>,
}

impl GetConvictionsByRoundRequest {
    pub fn new() -> GetConvictionsByRoundRequest {
        GetConvictionsByRoundRequest { round_id: None }
    }
}
