/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRoundsRequest {
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<i64>,
    #[serde(rename = "before", skip_serializing_if = "Option::is_none")]
    pub before: Option<i64>,
}

impl GetRoundsRequest {
    pub fn new() -> GetRoundsRequest {
        GetRoundsRequest {
            after: None,
            before: None,
        }
    }
}
