/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventStreamResponse {
    #[serde(rename = "batchFailed", skip_serializing_if = "Option::is_none")]
    pub batch_failed: Option<models::BatchFailedEvent>,
    #[serde(rename = "batchFinalization", skip_serializing_if = "Option::is_none")]
    pub batch_finalization: Option<models::BatchFinalizationEvent>,
    #[serde(rename = "batchFinalized", skip_serializing_if = "Option::is_none")]
    pub batch_finalized: Option<models::BatchFinalizedEvent>,
    #[serde(rename = "batchStarted", skip_serializing_if = "Option::is_none")]
    pub batch_started: Option<models::BatchStartedEvent>,
    #[serde(rename = "heartbeat", skip_serializing_if = "Option::is_none")]
    pub heartbeat: Option<serde_json::Value>,
    #[serde(rename = "treeNonces", skip_serializing_if = "Option::is_none")]
    pub tree_nonces: Option<models::TreeNoncesEvent>,
    #[serde(
        rename = "treeNoncesAggregated",
        skip_serializing_if = "Option::is_none"
    )]
    pub tree_nonces_aggregated: Option<models::TreeNoncesAggregatedEvent>,
    #[serde(rename = "treeSignature", skip_serializing_if = "Option::is_none")]
    pub tree_signature: Option<models::TreeSignatureEvent>,
    #[serde(rename = "treeSigningStarted", skip_serializing_if = "Option::is_none")]
    pub tree_signing_started: Option<models::TreeSigningStartedEvent>,
    #[serde(rename = "treeTx", skip_serializing_if = "Option::is_none")]
    pub tree_tx: Option<models::TreeTxEvent>,
}

impl GetEventStreamResponse {
    pub fn new() -> GetEventStreamResponse {
        GetEventStreamResponse {
            batch_failed: None,
            batch_finalization: None,
            batch_finalized: None,
            batch_started: None,
            heartbeat: None,
            tree_nonces: None,
            tree_nonces_aggregated: None,
            tree_signature: None,
            tree_signing_started: None,
            tree_tx: None,
        }
    }
}
