/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVtxoTreeLeavesResponse {
    #[serde(rename = "leaves", skip_serializing_if = "Option::is_none")]
    pub leaves: Option<Vec<models::IndexerOutpoint>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::IndexerPageResponse>,
}

impl GetVtxoTreeLeavesResponse {
    pub fn new() -> GetVtxoTreeLeavesResponse {
        GetVtxoTreeLeavesResponse {
            leaves: None,
            page: None,
        }
    }
}
