/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVtxoChainResponse {
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<Vec<models::IndexerChain>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::IndexerPageResponse>,
}

impl GetVtxoChainResponse {
    pub fn new() -> GetVtxoChainResponse {
        GetVtxoChainResponse {
            chain: None,
            page: None,
        }
    }
}
