/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBatchSweepTransactionsResponse {
    #[serde(rename = "sweptBy", skip_serializing_if = "Option::is_none")]
    pub swept_by: Option<Vec<String>>,
}

impl GetBatchSweepTransactionsResponse {
    pub fn new() -> GetBatchSweepTransactionsResponse {
        GetBatchSweepTransactionsResponse { swept_by: None }
    }
}
