/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRoundDetailsResponse {
    #[serde(rename = "commitmentTxid", skip_serializing_if = "Option::is_none")]
    pub commitment_txid: Option<String>,
    #[serde(rename = "endedAt", skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<i64>,
    #[serde(rename = "exitAddresses", skip_serializing_if = "Option::is_none")]
    pub exit_addresses: Option<Vec<String>>,
    #[serde(rename = "forfeitedAmount", skip_serializing_if = "Option::is_none")]
    pub forfeited_amount: Option<String>,
    #[serde(rename = "inputsVtxos", skip_serializing_if = "Option::is_none")]
    pub inputs_vtxos: Option<Vec<String>>,
    #[serde(rename = "outputsVtxos", skip_serializing_if = "Option::is_none")]
    pub outputs_vtxos: Option<Vec<String>>,
    #[serde(rename = "roundId", skip_serializing_if = "Option::is_none")]
    pub round_id: Option<String>,
    #[serde(rename = "startedAt", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<i64>,
    #[serde(rename = "totalExitAmount", skip_serializing_if = "Option::is_none")]
    pub total_exit_amount: Option<String>,
    #[serde(rename = "totalFeeAmount", skip_serializing_if = "Option::is_none")]
    pub total_fee_amount: Option<String>,
    #[serde(rename = "totalVtxosAmount", skip_serializing_if = "Option::is_none")]
    pub total_vtxos_amount: Option<String>,
}

impl GetRoundDetailsResponse {
    pub fn new() -> GetRoundDetailsResponse {
        GetRoundDetailsResponse {
            commitment_txid: None,
            ended_at: None,
            exit_addresses: None,
            forfeited_amount: None,
            inputs_vtxos: None,
            outputs_vtxos: None,
            round_id: None,
            started_at: None,
            total_exit_amount: None,
            total_fee_amount: None,
            total_vtxos_amount: None,
        }
    }
}
