/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IndexerTxType {
    #[serde(rename = "INDEXER_TX_TYPE_UNSPECIFIED")]
    IndexerTxTypeUnspecified,
    #[serde(rename = "INDEXER_TX_TYPE_RECEIVED")]
    IndexerTxTypeReceived,
    #[serde(rename = "INDEXER_TX_TYPE_SENT")]
    IndexerTxTypeSent,
}

impl std::fmt::Display for IndexerTxType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::IndexerTxTypeUnspecified => write!(f, "INDEXER_TX_TYPE_UNSPECIFIED"),
            Self::IndexerTxTypeReceived => write!(f, "INDEXER_TX_TYPE_RECEIVED"),
            Self::IndexerTxTypeSent => write!(f, "INDEXER_TX_TYPE_SENT"),
        }
    }
}

impl Default for IndexerTxType {
    fn default() -> IndexerTxType {
        Self::IndexerTxTypeUnspecified
    }
}
