/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IndexerChainedTxType {
    #[serde(rename = "INDEXER_CHAINED_TX_TYPE_UNSPECIFIED")]
    IndexerChainedTxTypeUnspecified,
    #[serde(rename = "INDEXER_CHAINED_TX_TYPE_COMMITMENT")]
    IndexerChainedTxTypeCommitment,
    #[serde(rename = "INDEXER_CHAINED_TX_TYPE_ARK")]
    IndexerChainedTxTypeArk,
    #[serde(rename = "INDEXER_CHAINED_TX_TYPE_TREE")]
    IndexerChainedTxTypeTree,
    #[serde(rename = "INDEXER_CHAINED_TX_TYPE_CHECKPOINT")]
    IndexerChainedTxTypeCheckpoint,
}

impl std::fmt::Display for IndexerChainedTxType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::IndexerChainedTxTypeUnspecified => {
                write!(f, "INDEXER_CHAINED_TX_TYPE_UNSPECIFIED")
            }
            Self::IndexerChainedTxTypeCommitment => write!(f, "INDEXER_CHAINED_TX_TYPE_COMMITMENT"),
            Self::IndexerChainedTxTypeArk => write!(f, "INDEXER_CHAINED_TX_TYPE_ARK"),
            Self::IndexerChainedTxTypeTree => write!(f, "INDEXER_CHAINED_TX_TYPE_TREE"),
            Self::IndexerChainedTxTypeCheckpoint => write!(f, "INDEXER_CHAINED_TX_TYPE_CHECKPOINT"),
        }
    }
}

impl Default for IndexerChainedTxType {
    fn default() -> IndexerChainedTxType {
        Self::IndexerChainedTxTypeUnspecified
    }
}
