/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexerSubscriptionEvent {
    #[serde(rename = "checkpointTxs", skip_serializing_if = "Option::is_none")]
    pub checkpoint_txs: Option<std::collections::HashMap<String, models::IndexerTxData>>,
    #[serde(rename = "newVtxos", skip_serializing_if = "Option::is_none")]
    pub new_vtxos: Option<Vec<models::IndexerVtxo>>,
    #[serde(rename = "scripts", skip_serializing_if = "Option::is_none")]
    pub scripts: Option<Vec<String>>,
    #[serde(rename = "spentVtxos", skip_serializing_if = "Option::is_none")]
    pub spent_vtxos: Option<Vec<models::IndexerVtxo>>,
    #[serde(rename = "sweptVtxos", skip_serializing_if = "Option::is_none")]
    pub swept_vtxos: Option<Vec<models::IndexerVtxo>>,
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<String>,
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
}

impl IndexerSubscriptionEvent {
    pub fn new() -> IndexerSubscriptionEvent {
        IndexerSubscriptionEvent {
            checkpoint_txs: None,
            new_vtxos: None,
            scripts: None,
            spent_vtxos: None,
            swept_vtxos: None,
            tx: None,
            txid: None,
        }
    }
}
