/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexerNode {
    /// vout -> txid
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
}

impl IndexerNode {
    pub fn new() -> IndexerNode {
        IndexerNode {
            children: None,
            txid: None,
        }
    }
}
