/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexerBatch {
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<i64>,
    #[serde(rename = "swept", skip_serializing_if = "Option::is_none")]
    pub swept: Option<bool>,
    #[serde(rename = "totalOutputAmount", skip_serializing_if = "Option::is_none")]
    pub total_output_amount: Option<i32>,
    #[serde(rename = "totalOutputVtxos", skip_serializing_if = "Option::is_none")]
    pub total_output_vtxos: Option<i32>,
}

impl IndexerBatch {
    pub fn new() -> IndexerBatch {
        IndexerBatch {
            expires_at: None,
            swept: None,
            total_output_amount: None,
            total_output_vtxos: None,
        }
    }
}
