/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Input {
    #[serde(rename = "outpoint", skip_serializing_if = "Option::is_none")]
    pub outpoint: Option<models::Outpoint>,
    #[serde(rename = "taprootTree", skip_serializing_if = "Option::is_none")]
    pub taproot_tree: Option<models::Tapscripts>,
}

impl Input {
    pub fn new() -> Input {
        Input {
            outpoint: None,
            taproot_tree: None,
        }
    }
}
