/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntentFeeInfo {
    #[serde(rename = "offchainInput", skip_serializing_if = "Option::is_none")]
    pub offchain_input: Option<String>,
    #[serde(rename = "offchainOutput", skip_serializing_if = "Option::is_none")]
    pub offchain_output: Option<String>,
    #[serde(rename = "onchainInput", skip_serializing_if = "Option::is_none")]
    pub onchain_input: Option<String>,
    #[serde(rename = "onchainOutput", skip_serializing_if = "Option::is_none")]
    pub onchain_output: Option<String>,
}

impl IntentFeeInfo {
    pub fn new() -> IntentFeeInfo {
        IntentFeeInfo {
            offchain_input: None,
            offchain_output: None,
            onchain_input: None,
            onchain_output: None,
        }
    }
}
