/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListIntentsRequest {
    #[serde(rename = "intentIds", skip_serializing_if = "Option::is_none")]
    pub intent_ids: Option<Vec<String>>,
}

impl ListIntentsRequest {
    pub fn new() -> ListIntentsRequest {
        ListIntentsRequest { intent_ids: None }
    }
}
