/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoadSignerRequest {
    #[serde(rename = "signerPrivateKey", skip_serializing_if = "Option::is_none")]
    pub signer_private_key: Option<String>,
    #[serde(rename = "signerUrl", skip_serializing_if = "Option::is_none")]
    pub signer_url: Option<String>,
}

impl LoadSignerRequest {
    pub fn new() -> LoadSignerRequest {
        LoadSignerRequest {
            signer_private_key: None,
            signer_url: None,
        }
    }
}
