/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifyTopics {
    #[serde(rename = "addTopics", skip_serializing_if = "Option::is_none")]
    pub add_topics: Option<Vec<String>>,
    #[serde(rename = "removeTopics", skip_serializing_if = "Option::is_none")]
    pub remove_topics: Option<Vec<String>>,
}

impl ModifyTopics {
    pub fn new() -> ModifyTopics {
        ModifyTopics {
            add_topics: None,
            remove_topics: None,
        }
    }
}
