/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Output {
    /// Amount to send in satoshis.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i32>,
    #[serde(rename = "onchainAddress", skip_serializing_if = "Option::is_none")]
    pub onchain_address: Option<String>,
    #[serde(rename = "vtxoScript", skip_serializing_if = "Option::is_none")]
    pub vtxo_script: Option<String>,
}

impl Output {
    pub fn new() -> Output {
        Output {
            amount: None,
            onchain_address: None,
            vtxo_script: None,
        }
    }
}
