/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingTx {
    #[serde(rename = "arkTxid", skip_serializing_if = "Option::is_none")]
    pub ark_txid: Option<String>,
    #[serde(rename = "finalArkTx", skip_serializing_if = "Option::is_none")]
    pub final_ark_tx: Option<String>,
    #[serde(
        rename = "signedCheckpointTxs",
        skip_serializing_if = "Option::is_none"
    )]
    pub signed_checkpoint_txs: Option<Vec<String>>,
}

impl PendingTx {
    pub fn new() -> PendingTx {
        PendingTx {
            ark_txid: None,
            final_ark_tx: None,
            signed_checkpoint_txs: None,
        }
    }
}
