/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterIntentResponse {
    #[serde(rename = "intentId", skip_serializing_if = "Option::is_none")]
    pub intent_id: Option<String>,
}

impl RegisterIntentResponse {
    pub fn new() -> RegisterIntentResponse {
        RegisterIntentResponse { intent_id: None }
    }
}
