/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterIntentRequest {
    /// an intent proof that embeds the outpoints to be spent and new ones to be created, as well
    /// as the proof of funds.
    #[serde(rename = "intent", skip_serializing_if = "Option::is_none")]
    pub intent: Option<models::Intent>,
}

impl RegisterIntentRequest {
    pub fn new() -> RegisterIntentRequest {
        RegisterIntentRequest { intent: None }
    }
}
