/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledSweep {
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::SweepableOutput>>,
    #[serde(rename = "roundId", skip_serializing_if = "Option::is_none")]
    pub round_id: Option<String>,
}

impl ScheduledSweep {
    pub fn new() -> ScheduledSweep {
        ScheduledSweep {
            outputs: None,
            round_id: None,
        }
    }
}
