/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitTreeSignaturesRequest {
    #[serde(rename = "batchId", skip_serializing_if = "Option::is_none")]
    pub batch_id: Option<String>,
    #[serde(rename = "pubkey", skip_serializing_if = "Option::is_none")]
    pub pubkey: Option<String>,
    #[serde(rename = "treeSignatures", skip_serializing_if = "Option::is_none")]
    pub tree_signatures: Option<std::collections::HashMap<String, String>>,
}

impl SubmitTreeSignaturesRequest {
    pub fn new() -> SubmitTreeSignaturesRequest {
        SubmitTreeSignaturesRequest {
            batch_id: None,
            pubkey: None,
            tree_signatures: None,
        }
    }
}
