/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitTxRequest {
    #[serde(rename = "checkpointTxs", skip_serializing_if = "Option::is_none")]
    pub checkpoint_txs: Option<Vec<String>>,
    #[serde(rename = "signedArkTx", skip_serializing_if = "Option::is_none")]
    pub signed_ark_tx: Option<String>,
}

impl SubmitTxRequest {
    pub fn new() -> SubmitTxRequest {
        SubmitTxRequest {
            checkpoint_txs: None,
            signed_ark_tx: None,
        }
    }
}
