/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// SubscriptionFilter : SubscriptionFilter is the payload carried by GetSubscription's initial
/// filter and by UpdateSubscription. See UpdateSubscriptionRequest for the per-call semantics of
/// each field.  At runtime, a tx event is dispatched to a subscription when any of its expressions
/// evaluates to true on the event's tx, OR when the event carries a vtxo whose script is in the
/// subscription's script set.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionFilter {
    /// CEL expressions evaluated against each indexed tx envelope. The indexer combines them with
    /// OR.
    #[serde(rename = "expressions", skip_serializing_if = "Option::is_none")]
    pub expressions: Option<Vec<String>>,
    /// Script add/remove operations. Will be migrated to a CEL formula in a future protocol
    /// version and removed.
    #[serde(rename = "scripts", skip_serializing_if = "Option::is_none")]
    pub scripts: Option<models::ScriptFilter>,
}

impl SubscriptionFilter {
    /// SubscriptionFilter is the payload carried by GetSubscription's initial filter and by
    /// UpdateSubscription. See UpdateSubscriptionRequest for the per-call semantics of each field.
    /// At runtime, a tx event is dispatched to a subscription when any of its expressions evaluates
    /// to true on the event's tx, OR when the event carries a vtxo whose script is in the
    /// subscription's script set.
    pub fn new() -> SubscriptionFilter {
        SubscriptionFilter {
            expressions: None,
            scripts: None,
        }
    }
}
