/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TreeNoncesAggregatedEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "treeNonces", skip_serializing_if = "Option::is_none")]
    pub tree_nonces: Option<std::collections::HashMap<String, String>>,
}

impl TreeNoncesAggregatedEvent {
    pub fn new() -> TreeNoncesAggregatedEvent {
        TreeNoncesAggregatedEvent {
            id: None,
            tree_nonces: None,
        }
    }
}
