/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TreeNoncesEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// pubkey -> musig2 public nonce
    #[serde(rename = "nonces", skip_serializing_if = "Option::is_none")]
    pub nonces: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<Vec<String>>,
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
}

impl TreeNoncesEvent {
    pub fn new() -> TreeNoncesEvent {
        TreeNoncesEvent {
            id: None,
            nonces: None,
            topic: None,
            txid: None,
        }
    }
}
