/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TreeSignatureEvent {
    #[serde(rename = "batchIndex", skip_serializing_if = "Option::is_none")]
    pub batch_index: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<Vec<String>>,
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
}

impl TreeSignatureEvent {
    pub fn new() -> TreeSignatureEvent {
        TreeSignatureEvent {
            batch_index: None,
            id: None,
            signature: None,
            topic: None,
            txid: None,
        }
    }
}
