/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TxNotification {
    /// This field is set only in case of offchain tx.  key: outpoint, value: checkpoint txid
    #[serde(rename = "checkpointTxs", skip_serializing_if = "Option::is_none")]
    pub checkpoint_txs: Option<std::collections::HashMap<String, models::TxData>>,
    #[serde(rename = "spendableVtxos", skip_serializing_if = "Option::is_none")]
    pub spendable_vtxos: Option<Vec<models::Vtxo>>,
    #[serde(rename = "spentVtxos", skip_serializing_if = "Option::is_none")]
    pub spent_vtxos: Option<Vec<models::Vtxo>>,
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<String>,
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
}

impl TxNotification {
    pub fn new() -> TxNotification {
        TxNotification {
            checkpoint_txs: None,
            spendable_vtxos: None,
            spent_vtxos: None,
            tx: None,
            txid: None,
        }
    }
}
