/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnsubscribeForScriptsRequest {
    /// If empty, unsubscribe all scripts
    #[serde(rename = "scripts", skip_serializing_if = "Option::is_none")]
    pub scripts: Option<Vec<String>>,
    #[serde(rename = "subscriptionId", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
}

impl UnsubscribeForScriptsRequest {
    pub fn new() -> UnsubscribeForScriptsRequest {
        UnsubscribeForScriptsRequest {
            scripts: None,
            subscription_id: None,
        }
    }
}
