/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// UpdateStreamTopicsRequest : Adding and removing topics can both be supplied in the same request,
/// allowing for simultaneous changes. overwrite_topics will take precedence, and if set, then the
/// add/remove topics are ignored. The stream_id is required.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateStreamTopicsRequest {
    #[serde(rename = "modify", skip_serializing_if = "Option::is_none")]
    pub modify: Option<models::ModifyTopics>,
    #[serde(rename = "overwrite", skip_serializing_if = "Option::is_none")]
    pub overwrite: Option<models::OverwriteTopics>,
    #[serde(rename = "streamId", skip_serializing_if = "Option::is_none")]
    pub stream_id: Option<String>,
}

impl UpdateStreamTopicsRequest {
    /// Adding and removing topics can both be supplied in the same request, allowing for
    /// simultaneous changes. overwrite_topics will take precedence, and if set, then the add/remove
    /// topics are ignored. The stream_id is required.
    pub fn new() -> UpdateStreamTopicsRequest {
        UpdateStreamTopicsRequest {
            modify: None,
            overwrite: None,
            stream_id: None,
        }
    }
}
