/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

/// UpdateSubscriptionRequest : UpdateSubscriptionRequest mutates an existing subscription. Both
/// filter fields are optional and may be set together. The subscription_id must be non-empty and
/// the filter must be present; otherwise InvalidArgument is returned.  Expressions
/// (filter.expressions): - Always overwritten as a whole. The field's contents replace any
/// previously-set expressions even when the list is empty (which clears them entirely). - Duplicate
/// expressions are deduplicated, since the underlying set is keyed by expression string. - Bounded
/// by a server-side per-subscription cap; exceeding it returns InvalidArgument.  Scripts
/// (filter.scripts): - When the scripts field is unset, scripts are left untouched. - When set with
/// both `add` and `remove` empty, the call clears all scripts (mirrors UnsubscribeForScripts with
/// an empty scripts list). - When set with `add` non-empty, those scripts are added. - When set
/// with `remove` non-empty, those scripts are removed. - `add` and `remove` may be combined in a
/// single call. When the two lists overlap, remove takes precedence, since add is applied first and
/// remove second. - Both operations are idempotent: adding an already-subscribed script is a no-op,
/// and removing an unsubscribed script is a no-op.  Atomicity: - All inputs (CEL expressions,
/// scripts to add, scripts to remove) are validated before any state is mutated. If any single
/// input fails validation, no mutations are applied and even valid entries in the same request are
/// discarded. An InvalidArgument response therefore guarantees the subscription is unchanged. - A
/// successful response guarantees all requested mutations were applied.  Errors: - NotFound:
/// subscription_id does not match a live subscription. - InvalidArgument: any CEL compile error,
/// any script parse error, or the expressions cap exceeded.  GetSubscription initial filter: - The
/// same SubscriptionFilter shape is accepted by GetSubscriptionRequest.filter on stream creation,
/// with the same semantics as above and two exceptions. - `scripts.remove` is ignored on creation,
/// since a freshly-created subscription has no scripts to remove. - When `scripts` is set with both
/// `add` and `remove` empty on creation, the clear-all behavior does not fire either, since there
/// is nothing to clear. An empty SubscriptionFilter is therefore a no-op on creation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSubscriptionRequest {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<models::SubscriptionFilter>,
    #[serde(rename = "subscriptionId", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
}

impl UpdateSubscriptionRequest {
    /// UpdateSubscriptionRequest mutates an existing subscription. Both filter fields are optional
    /// and may be set together. The subscription_id must be non-empty and the filter must be
    /// present; otherwise InvalidArgument is returned.  Expressions (filter.expressions): - Always
    /// overwritten as a whole. The field's contents replace any previously-set expressions even
    /// when the list is empty (which clears them entirely). - Duplicate expressions are
    /// deduplicated, since the underlying set is keyed by expression string. - Bounded by a
    /// server-side per-subscription cap; exceeding it returns InvalidArgument.  Scripts
    /// (filter.scripts): - When the scripts field is unset, scripts are left untouched. - When set
    /// with both `add` and `remove` empty, the call clears all scripts (mirrors
    /// UnsubscribeForScripts with an empty scripts list). - When set with `add` non-empty, those
    /// scripts are added. - When set with `remove` non-empty, those scripts are removed. - `add`
    /// and `remove` may be combined in a single call. When the two lists overlap, remove takes
    /// precedence, since add is applied first and remove second. - Both operations are idempotent:
    /// adding an already-subscribed script is a no-op, and removing an unsubscribed script is a
    /// no-op.  Atomicity: - All inputs (CEL expressions, scripts to add, scripts to remove) are
    /// validated before any state is mutated. If any single input fails validation, no mutations
    /// are applied and even valid entries in the same request are discarded. An InvalidArgument
    /// response therefore guarantees the subscription is unchanged. - A successful response
    /// guarantees all requested mutations were applied.  Errors: - NotFound: subscription_id does
    /// not match a live subscription. - InvalidArgument: any CEL compile error, any script parse
    /// error, or the expressions cap exceeded.  GetSubscription initial filter: - The same
    /// SubscriptionFilter shape is accepted by GetSubscriptionRequest.filter on stream creation,
    /// with the same semantics as above and two exceptions. - `scripts.remove` is ignored on
    /// creation, since a freshly-created subscription has no scripts to remove. - When `scripts` is
    /// set with both `add` and `remove` empty on creation, the clear-all behavior does not fire
    /// either, since there is nothing to clear. An empty SubscriptionFilter is therefore a no-op on
    /// creation.
    pub fn new() -> UpdateSubscriptionRequest {
        UpdateSubscriptionRequest {
            filter: None,
            subscription_id: None,
        }
    }
}
