/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1BatchFinalizedEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "commitmentTxid", skip_serializing_if = "Option::is_none")]
    pub commitment_txid: Option<String>,
}

impl V1BatchFinalizedEvent {
    pub fn new() -> V1BatchFinalizedEvent {
        V1BatchFinalizedEvent {
            id: None,
            commitment_txid: None,
        }
    }
}
