/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1BatchFinalizationEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "commitmentTx", skip_serializing_if = "Option::is_none")]
    pub commitment_tx: Option<String>,
}

impl V1BatchFinalizationEvent {
    pub fn new() -> V1BatchFinalizationEvent {
        V1BatchFinalizationEvent {
            id: None,
            commitment_tx: None,
        }
    }
}
