/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1BatchStartedEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "intentIdHashes", skip_serializing_if = "Option::is_none")]
    pub intent_id_hashes: Option<Vec<String>>,
    #[serde(rename = "batchExpiry", skip_serializing_if = "Option::is_none")]
    pub batch_expiry: Option<String>,
}

impl V1BatchStartedEvent {
    pub fn new() -> V1BatchStartedEvent {
        V1BatchStartedEvent {
            id: None,
            intent_id_hashes: None,
            batch_expiry: None,
        }
    }
}
