/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ConfirmRegistrationRequest {
    #[serde(rename = "intentId", skip_serializing_if = "Option::is_none")]
    pub intent_id: Option<String>,
}

impl V1ConfirmRegistrationRequest {
    pub fn new() -> V1ConfirmRegistrationRequest {
        V1ConfirmRegistrationRequest { intent_id: None }
    }
}
