/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1DeleteIntentRequest {
    #[serde(rename = "proof", skip_serializing_if = "Option::is_none")]
    pub proof: Option<models::V1Bip322Signature>,
}

impl V1DeleteIntentRequest {
    pub fn new() -> V1DeleteIntentRequest {
        V1DeleteIntentRequest { proof: None }
    }
}
