/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetVtxoTreeLeavesResponse {
    #[serde(rename = "leaves", skip_serializing_if = "Option::is_none")]
    pub leaves: Option<Vec<models::V1IndexerOutpoint>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::V1IndexerPageResponse>,
}

impl V1GetVtxoTreeLeavesResponse {
    pub fn new() -> V1GetVtxoTreeLeavesResponse {
        V1GetVtxoTreeLeavesResponse {
            leaves: None,
            page: None,
        }
    }
}
