/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetVtxoTreeResponse {
    #[serde(rename = "vtxoTree", skip_serializing_if = "Option::is_none")]
    pub vtxo_tree: Option<Vec<models::V1IndexerNode>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::V1IndexerPageResponse>,
}

impl V1GetVtxoTreeResponse {
    pub fn new() -> V1GetVtxoTreeResponse {
        V1GetVtxoTreeResponse {
            vtxo_tree: None,
            page: None,
        }
    }
}
