/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetBatchSweepTransactionsResponse {
    #[serde(rename = "sweptBy", skip_serializing_if = "Option::is_none")]
    pub swept_by: Option<Vec<String>>,
}

impl V1GetBatchSweepTransactionsResponse {
    pub fn new() -> V1GetBatchSweepTransactionsResponse {
        V1GetBatchSweepTransactionsResponse { swept_by: None }
    }
}
