/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetCommitmentTxResponse {
    #[serde(rename = "startedAt", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    #[serde(rename = "endedAt", skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<String>,
    #[serde(rename = "batches", skip_serializing_if = "Option::is_none")]
    pub batches: Option<std::collections::HashMap<String, models::V1IndexerBatch>>,
    #[serde(rename = "totalInputAmount", skip_serializing_if = "Option::is_none")]
    pub total_input_amount: Option<String>,
    #[serde(rename = "totalInputVtxos", skip_serializing_if = "Option::is_none")]
    pub total_input_vtxos: Option<i32>,
    #[serde(rename = "totalOutputAmount", skip_serializing_if = "Option::is_none")]
    pub total_output_amount: Option<String>,
    #[serde(rename = "totalOutputVtxos", skip_serializing_if = "Option::is_none")]
    pub total_output_vtxos: Option<i32>,
}

impl V1GetCommitmentTxResponse {
    pub fn new() -> V1GetCommitmentTxResponse {
        V1GetCommitmentTxResponse {
            started_at: None,
            ended_at: None,
            batches: None,
            total_input_amount: None,
            total_input_vtxos: None,
            total_output_amount: None,
            total_output_vtxos: None,
        }
    }
}
