/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetInfoResponse {
    #[serde(rename = "signerPubkey", skip_serializing_if = "Option::is_none")]
    pub signer_pubkey: Option<String>,
    #[serde(rename = "vtxoTreeExpiry", skip_serializing_if = "Option::is_none")]
    pub vtxo_tree_expiry: Option<String>,
    #[serde(
        rename = "unilateralExitDelay",
        skip_serializing_if = "Option::is_none"
    )]
    pub unilateral_exit_delay: Option<String>,
    #[serde(rename = "roundInterval", skip_serializing_if = "Option::is_none")]
    pub round_interval: Option<String>,
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    #[serde(rename = "dust", skip_serializing_if = "Option::is_none")]
    pub dust: Option<String>,
    #[serde(rename = "forfeitAddress", skip_serializing_if = "Option::is_none")]
    pub forfeit_address: Option<String>,
    #[serde(rename = "marketHour", skip_serializing_if = "Option::is_none")]
    pub market_hour: Option<models::V1MarketHour>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "utxoMinAmount", skip_serializing_if = "Option::is_none")]
    pub utxo_min_amount: Option<String>,
    #[serde(rename = "utxoMaxAmount", skip_serializing_if = "Option::is_none")]
    pub utxo_max_amount: Option<String>,
    #[serde(rename = "vtxoMinAmount", skip_serializing_if = "Option::is_none")]
    pub vtxo_min_amount: Option<String>,
    #[serde(rename = "vtxoMaxAmount", skip_serializing_if = "Option::is_none")]
    pub vtxo_max_amount: Option<String>,
    #[serde(rename = "boardingExitDelay", skip_serializing_if = "Option::is_none")]
    pub boarding_exit_delay: Option<String>,
}

impl V1GetInfoResponse {
    pub fn new() -> V1GetInfoResponse {
        V1GetInfoResponse {
            signer_pubkey: None,
            vtxo_tree_expiry: None,
            unilateral_exit_delay: None,
            round_interval: None,
            network: None,
            dust: None,
            forfeit_address: None,
            market_hour: None,
            version: None,
            utxo_min_amount: None,
            utxo_max_amount: None,
            vtxo_min_amount: None,
            vtxo_max_amount: None,
            boarding_exit_delay: None,
        }
    }
}
