/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetSubscriptionResponse {
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    #[serde(rename = "scripts", skip_serializing_if = "Option::is_none")]
    pub scripts: Option<Vec<String>>,
    #[serde(rename = "newVtxos", skip_serializing_if = "Option::is_none")]
    pub new_vtxos: Option<Vec<models::V1IndexerVtxo>>,
    #[serde(rename = "spentVtxos", skip_serializing_if = "Option::is_none")]
    pub spent_vtxos: Option<Vec<models::V1IndexerVtxo>>,
    #[serde(rename = "tx", skip_serializing_if = "Option::is_none")]
    pub tx: Option<String>,
    #[serde(rename = "checkpointTxs", skip_serializing_if = "Option::is_none")]
    pub checkpoint_txs: Option<std::collections::HashMap<String, models::V1IndexerTxData>>,
}

impl V1GetSubscriptionResponse {
    pub fn new() -> V1GetSubscriptionResponse {
        V1GetSubscriptionResponse {
            txid: None,
            scripts: None,
            new_vtxos: None,
            spent_vtxos: None,
            tx: None,
            checkpoint_txs: None,
        }
    }
}
