/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetTransactionsStreamResponse {
    #[serde(rename = "commitmentTx", skip_serializing_if = "Option::is_none")]
    pub commitment_tx: Option<models::V1TxNotification>,
    #[serde(rename = "arkTx", skip_serializing_if = "Option::is_none")]
    pub ark_tx: Option<models::V1TxNotification>,
}

impl V1GetTransactionsStreamResponse {
    pub fn new() -> V1GetTransactionsStreamResponse {
        V1GetTransactionsStreamResponse {
            commitment_tx: None,
            ark_tx: None,
        }
    }
}
