/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GetForfeitTxsResponse {
    #[serde(rename = "txids", skip_serializing_if = "Option::is_none")]
    pub txids: Option<Vec<String>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::V1IndexerPageResponse>,
}

impl V1GetForfeitTxsResponse {
    pub fn new() -> V1GetForfeitTxsResponse {
        V1GetForfeitTxsResponse {
            txids: None,
            page: None,
        }
    }
}
