/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1IndexerChain {
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::V1IndexerChainedTxType>,
    #[serde(rename = "spends", skip_serializing_if = "Option::is_none")]
    pub spends: Option<Vec<String>>,
}

impl V1IndexerChain {
    pub fn new() -> V1IndexerChain {
        V1IndexerChain {
            txid: None,
            expires_at: None,
            r#type: None,
            spends: None,
        }
    }
}
