/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1IndexerBatch {
    #[serde(rename = "totalOutputAmount", skip_serializing_if = "Option::is_none")]
    pub total_output_amount: Option<String>,
    #[serde(rename = "totalOutputVtxos", skip_serializing_if = "Option::is_none")]
    pub total_output_vtxos: Option<i32>,
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "swept", skip_serializing_if = "Option::is_none")]
    pub swept: Option<bool>,
}

impl V1IndexerBatch {
    pub fn new() -> V1IndexerBatch {
        V1IndexerBatch {
            total_output_amount: None,
            total_output_vtxos: None,
            expires_at: None,
            swept: None,
        }
    }
}
