/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1IndexerOutpoint {
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    #[serde(rename = "vout", skip_serializing_if = "Option::is_none")]
    pub vout: Option<i64>,
}

impl V1IndexerOutpoint {
    pub fn new() -> V1IndexerOutpoint {
        V1IndexerOutpoint {
            txid: None,
            vout: None,
        }
    }
}
