/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1RegisterIntentRequest {
    #[serde(rename = "intent", skip_serializing_if = "Option::is_none")]
    pub intent: Option<models::V1Bip322Signature>,
}

impl V1RegisterIntentRequest {
    pub fn new() -> V1RegisterIntentRequest {
        V1RegisterIntentRequest { intent: None }
    }
}
