/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SubmitTxRequest {
    #[serde(rename = "signedArkTx", skip_serializing_if = "Option::is_none")]
    pub signed_ark_tx: Option<String>,
    #[serde(rename = "checkpointTxs", skip_serializing_if = "Option::is_none")]
    pub checkpoint_txs: Option<Vec<String>>,
}

impl V1SubmitTxRequest {
    pub fn new() -> V1SubmitTxRequest {
        V1SubmitTxRequest {
            signed_ark_tx: None,
            checkpoint_txs: None,
        }
    }
}
