/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SubmitTreeNoncesRequest {
    #[serde(rename = "batchId", skip_serializing_if = "Option::is_none")]
    pub batch_id: Option<String>,
    #[serde(rename = "pubkey", skip_serializing_if = "Option::is_none")]
    pub pubkey: Option<String>,
    #[serde(rename = "treeNonces", skip_serializing_if = "Option::is_none")]
    pub tree_nonces: Option<String>,
}

impl V1SubmitTreeNoncesRequest {
    pub fn new() -> V1SubmitTreeNoncesRequest {
        V1SubmitTreeNoncesRequest {
            batch_id: None,
            pubkey: None,
            tree_nonces: None,
        }
    }
}
