/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TreeNoncesAggregatedEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "treeNonces", skip_serializing_if = "Option::is_none")]
    pub tree_nonces: Option<String>,
}

impl V1TreeNoncesAggregatedEvent {
    pub fn new() -> V1TreeNoncesAggregatedEvent {
        V1TreeNoncesAggregatedEvent {
            id: None,
            tree_nonces: None,
        }
    }
}
