/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TreeSigningStartedEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "cosignersPubkeys", skip_serializing_if = "Option::is_none")]
    pub cosigners_pubkeys: Option<Vec<String>>,
    #[serde(
        rename = "unsignedCommitmentTx",
        skip_serializing_if = "Option::is_none"
    )]
    pub unsigned_commitment_tx: Option<String>,
}

impl V1TreeSigningStartedEvent {
    pub fn new() -> V1TreeSigningStartedEvent {
        V1TreeSigningStartedEvent {
            id: None,
            cosigners_pubkeys: None,
            unsigned_commitment_tx: None,
        }
    }
}
