/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TreeSignatureEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<Vec<String>>,
    #[serde(rename = "batchIndex", skip_serializing_if = "Option::is_none")]
    pub batch_index: Option<i32>,
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

impl V1TreeSignatureEvent {
    pub fn new() -> V1TreeSignatureEvent {
        V1TreeSignatureEvent {
            id: None,
            topic: None,
            batch_index: None,
            txid: None,
            signature: None,
        }
    }
}
