/*
 * Ark API
 *
 * Combined Ark Service and Indexer API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1UnsubscribeForScriptsRequest {
    #[serde(rename = "subscriptionId", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
    #[serde(rename = "scripts", skip_serializing_if = "Option::is_none")]
    pub scripts: Option<Vec<String>>,
}

impl V1UnsubscribeForScriptsRequest {
    pub fn new() -> V1UnsubscribeForScriptsRequest {
        V1UnsubscribeForScriptsRequest {
            subscription_id: None,
            scripts: None,
        }
    }
}
