/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vtxo {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i32>,
    #[serde(rename = "arkTxid", skip_serializing_if = "Option::is_none")]
    pub ark_txid: Option<String>,
    #[serde(rename = "commitmentTxids", skip_serializing_if = "Option::is_none")]
    pub commitment_txids: Option<Vec<String>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "isPreconfirmed", skip_serializing_if = "Option::is_none")]
    pub is_preconfirmed: Option<bool>,
    #[serde(rename = "isSpent", skip_serializing_if = "Option::is_none")]
    pub is_spent: Option<bool>,
    #[serde(rename = "isSwept", skip_serializing_if = "Option::is_none")]
    pub is_swept: Option<bool>,
    #[serde(rename = "isUnrolled", skip_serializing_if = "Option::is_none")]
    pub is_unrolled: Option<bool>,
    #[serde(rename = "outpoint", skip_serializing_if = "Option::is_none")]
    pub outpoint: Option<models::Outpoint>,
    #[serde(rename = "script", skip_serializing_if = "Option::is_none")]
    pub script: Option<String>,
    #[serde(rename = "settledBy", skip_serializing_if = "Option::is_none")]
    pub settled_by: Option<String>,
    #[serde(rename = "spentBy", skip_serializing_if = "Option::is_none")]
    pub spent_by: Option<String>,
}

impl Vtxo {
    pub fn new() -> Vtxo {
        Vtxo {
            amount: None,
            ark_txid: None,
            commitment_txids: None,
            created_at: None,
            expires_at: None,
            is_preconfirmed: None,
            is_spent: None,
            is_swept: None,
            is_unrolled: None,
            outpoint: None,
            script: None,
            settled_by: None,
            spent_by: None,
        }
    }
}
