/*
 * Ark API
 *
 * Combined Ark Service, Indexer, Admin, Signer Manager, and Wallet API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawRequest {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// if all=true, amount is ignored and all available balance is withdrawn including connectors
    /// account funds must be used carefully to not make connectors utxos unspendable, making
    /// forfeit txs invalid
    #[serde(rename = "all", skip_serializing_if = "Option::is_none")]
    pub all: Option<bool>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
}

impl WithdrawRequest {
    pub fn new() -> WithdrawRequest {
        WithdrawRequest {
            address: None,
            all: None,
            amount: None,
        }
    }
}
